### ISSUE TITLE
Counters under 200

### ISSUE THREAD

**Issue by lucy-brooker87** [nemo0/animated-counter#1]
Hi,  I can't seem to get the counter to work if I want it to count up to a figure under 200.

i.e. I wanted it to be 80 as I am doing 80%.

**Comment by nemo0** [comment]
Hey @lucy-brooker87! As we are doing this,
```jsx
const increment = Math.trunc(target / speed);
```
and the value of `speed = 200`, we are unable to get it to work because `Math.trunc(100/200)` gives `0`. Change the speed to less than or equal to `100` and it'll work.
